//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquidLeave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        public int LeaveApplicationId { get; set; }
        public int NumberOfDays { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public System.DateTime DateApplied { get; set; }
        public Nullable<System.DateTime> DateApprovedDenied { get; set; }
        public bool Status { get; set; }
        public string Comments { get; set; }
        public string UserId { get; set; }
        public bool Reviewed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
